# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [7]:
# Your code here
import random
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,8],[4,1],[7,2]])
C = np.array([[3,4],[1,8],[4,3]])

print("The Following is A.(B+C): \n")
print(A.dot(B+C))

print("\n The Following is A.B+A.C: \n")
print(A.dot(B)+A.dot(C))

The Following is A.(B+C): 

[[ 48  45]
 [111 123]
 [174 201]
 [237 279]]

 The Following is A.B+A.C: 

[[ 48  45]
 [111 123]
 [174 201]
 [237 279]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [9]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,8],[4,1],[7,2]])
C = np.array([[3,4],[1,8]])

print("The Following is A.(B.C): \n")
print(A.dot(B.dot(C)))

print("\n The Following is (A.B).C: \n")
print((A.dot(B)).dot(C))

The Following is A.(B.C): 

[[ 109  252]
 [ 259  672]
 [ 409 1092]
 [ 559 1512]]

 The Following is (A.B).C: 

[[ 109  252]
 [ 259  672]
 [ 409 1092]
 [ 559 1512]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [15]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[6,2,7],[8,1,8],[4,9,2]])


print("The Following is A.B: \n")
print(A.dot(B))

print("\n The Following is B.A: \n")
print(B.dot(A))

The Following is A.B: 

[[ 34  31  29]
 [ 88  67  80]
 [142 103 131]]

 The Following is B.A: 

[[ 63  78  93]
 [ 68  85 102]
 [ 54  69  84]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [17]:
x = np.array([[2], [6], [7]])
y = np.array([[3], [5], [9]])

left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
left == right
print(left)
print(right)

[[99]]
[[99]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [20]:
A = np.array([[2, 3], [1, 4], [7, 6]])
B = np.array([[5, 3], [2, 2]])

left = np.transpose(A.dot(B))
right = np.transpose(B).dot(np.transpose(A))
left == right
print(left)
print(right)

[[16 13 47]
 [12 11 33]]
[[16 13 47]
 [12 11 33]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 